# Site settings
title: Michael Thorne / Front-end Web Developer
strapline: Michael Thorne
description: Front-end web developer based in Cape Town, South Africa. Passionate about user experience, web standards and web performance. Also an avid traveller, cyclist and runner.
baseurl: ""
url: "https://www.userx.co.za"
permalink: :categories/:title/
google_analytics: G-XTWY8RP93Z
profile_github: michaelthorne
profile_google_plus: MichaelThorne_za
profile_instagram: mikkelz_za
profile_linkedin: thornemichael
profile_twitter: mikkelz_za
profile_youtube: mikkelzZA

# Build settings
markdown: kramdown
sass:
    style: :compressed
